# Program 2: Python program to implement the Data preprocessing techniques

In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv(r'/home/rashi/Documents/ML_Programs/Stats.csv')
print(data)

    Emp#  YearsOfExp  Salary in Rs.
0      1          10         126015
1      2           1          12598
2      3           8         100639
3      4          10         125351
4      5           2          25031
5      6           5          62630
6      7           9         112620
7      8           8         100639
8      9           4          50145
9     10           2          25232
10    11           9         112770
11    12           3          37512
12    13           4          50274
13    14           5          62768
14    15          10         125363
15    16           2          25226
16    17           6          75392
17    18           7          87779
18    19           7          87654
19    20           3          37592
20    21          10         125186
21    22           2          25187
22    23           9         113309
23    24           9         113112
24    25          10         125506


In [3]:
data.isnull() 

Emp#  YearsOfExp  Salary in Rs.
0   False       False          False
1   False       False          False
2   False       False          False
3   False       False          False
4   False       False          False
5   False       False          False
6   False       False          False
7   False       False          False
8   False       False          False
9   False       False          False
10  False       False          False
11  False       False          False
12  False       False          False
13  False       False          False
14  False       False          False
15  False       False          False
16  False       False          False
17  False       False          False
18  False       False          False
19  False       False          False
20  False       False          False
21  False       False          False
22  False       False          False
23  False       False          False
24  False       False          False

# Filling the Missing values in the dataset

In [4]:
#filling the missing values of the dataset
data=data.fillna(100)
print(data)

    Emp#  YearsOfExp  Salary in Rs.
0      1          10         126015
1      2           1          12598
2      3           8         100639
3      4          10         125351
4      5           2          25031
5      6           5          62630
6      7           9         112620
7      8           8         100639
8      9           4          50145
9     10           2          25232
10    11           9         112770
11    12           3          37512
12    13           4          50274
13    14           5          62768
14    15          10         125363
15    16           2          25226
16    17           6          75392
17    18           7          87779
18    19           7          87654
19    20           3          37592
20    21          10         125186
21    22           2          25187
22    23           9         113309
23    24           9         113112
24    25          10         125506


# Implement the Normalization - preprocessing technique

In [27]:
#Normalization- It is a Data Transformation technique. The process of the transforming the data into a smaller representation 
#to fall within the range of smaller values without altering the originality of the data.
#first Convert the dataFrame into numpy array using values function.
arr=data.values
print(arr)
#use the MinMaxScaler of the sklearn.preprocessing to normalize the data to fall between 0,1
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(arr)

[[  1.00000000e+01   1.26015000e+05]
 [  1.00000000e+00   1.25980000e+04]
 [  8.00000000e+00   1.00639000e+05]
 [  1.00000000e+01   1.25351000e+05]
 [  2.00000000e+00   2.50310000e+04]
 [  5.00000000e+00   6.26300000e+04]
 [  9.00000000e+00   1.12620000e+05]
 [  8.00000000e+00   1.00639000e+05]
 [  4.00000000e+00   5.01450000e+04]
 [  2.00000000e+00   2.52320000e+04]
 [  9.00000000e+00   1.12770000e+05]
 [  3.00000000e+00   3.75120000e+04]
 [  4.00000000e+00   5.02740000e+04]
 [  5.00000000e+00   6.27680000e+04]
 [  1.00000000e+01   1.25363000e+05]
 [  2.00000000e+00   2.52260000e+04]
 [  6.00000000e+00   7.53920000e+04]
 [  7.00000000e+00   8.77790000e+04]
 [  7.00000000e+00   8.76540000e+04]
 [  3.00000000e+00   3.75920000e+04]
 [  1.00000000e+01   1.25186000e+05]
 [  2.00000000e+00   2.51870000e+04]
 [  9.00000000e+00   1.13309000e+05]
 [  9.00000000e+00   1.13112000e+05]
 [  1.00000000e+01   1.25506000e+05]
 [  1.00000000e+02   1.00000000e+02]
 [  1.00000000e+02   1.00000000e+02]
 

In [28]:
#print the normalized values
print(rescaledX)

[[ 0.09090909  0.95053862]
 [ 0.          0.09434803]
 [ 0.07070707  0.75897393]
 [ 0.09090909  0.94552606]
 [ 0.01010101  0.18820536]
 [ 0.04040404  0.47204209]
 [ 0.08080808  0.8494191 ]
 [ 0.07070707  0.75897393]
 [ 0.03030303  0.3777922 ]
 [ 0.01010101  0.18972272]
 [ 0.08080808  0.85055146]
 [ 0.02020202  0.28242506]
 [ 0.03030303  0.37876603]
 [ 0.04040404  0.47308386]
 [ 0.09090909  0.94561664]
 [ 0.01010101  0.18967743]
 [ 0.05050505  0.56838307]
 [ 0.06060606  0.66189315]
 [ 0.06060606  0.66094952]
 [ 0.02020202  0.28302898]
 [ 0.09090909  0.94428046]
 [ 0.01010101  0.18938302]
 [ 0.08080808  0.8546204 ]
 [ 0.08080808  0.85313323]
 [ 0.09090909  0.94669616]
 [ 1.          0.        ]
 [ 1.          0.        ]
 [ 1.          0.        ]
 [ 0.09090909  1.        ]]


# Normalizing Only selected columns- Here normalizing  First column using reshape(-1,1)

In [52]:
rescaledX = scaler.fit_transform(arr[:,0].reshape(-1,1))
print(rescaledX)

[[ 0.09090909]
 [ 0.        ]
 [ 0.07070707]
 [ 0.09090909]
 [ 0.01010101]
 [ 0.04040404]
 [ 0.08080808]
 [ 0.07070707]
 [ 0.03030303]
 [ 0.01010101]
 [ 0.08080808]
 [ 0.02020202]
 [ 0.03030303]
 [ 0.04040404]
 [ 0.09090909]
 [ 0.01010101]
 [ 0.05050505]
 [ 0.06060606]
 [ 0.06060606]
 [ 0.02020202]
 [ 0.09090909]
 [ 0.01010101]
 [ 0.08080808]
 [ 0.08080808]
 [ 0.09090909]
 [ 1.        ]
 [ 1.        ]
 [ 1.        ]
 [ 0.09090909]]


# Implement the Standardization pre processing technique

In [29]:
#Standardization- It is a Data Transformation technique such that Mean of the attributes values becomes zero 
#and its standard deviation becomes 1
# Use scale function to im[plement the same
from sklearn import preprocessing
y_scaled = preprocessing.scale(arr)
print(y_scaled)

[[-0.21043719  1.21386587]
 [-0.52428922 -1.31939649]
 [-0.28018208  0.64707196]
 [-0.21043719  1.19903488]
 [-0.48941677 -1.04169517]
 [-0.38479943 -0.20189045]
 [-0.24530964  0.91467749]
 [-0.28018208  0.64707196]
 [-0.41967188 -0.48075323]
 [-0.48941677 -1.03720566]
 [-0.24530964  0.91802786]
 [-0.45454432 -0.76292172]
 [-0.41967188 -0.47787191]
 [-0.38479943 -0.19880811]
 [-0.21043719  1.19930291]
 [-0.48941677 -1.03733968]
 [-0.34992698  0.08315936]
 [-0.31505453  0.35983324]
 [-0.31505453  0.35704126]
 [-0.45454432 -0.76113486]
 [-0.21043719  1.19534947]
 [-0.48941677 -1.03821078]
 [-0.24530964  0.93006687]
 [-0.24530964  0.92566671]
 [-0.21043719  1.20249694]
 [ 2.92808315 -1.59854964]
 [ 2.92808315 -1.59854964]
 [ 2.92808315 -1.59854964]
 [-0.21043719  1.3602102 ]]


In [31]:
#Below code is used to cross verfiy the above standardization function using numpy mean and stadard deviation function
print(y_scaled[:,0].mean())
print(y_scaled[:,1].mean())
print(y_scaled[:,0].std())
print(y_scaled[:,1].std())

-1.30164078749e-16
-5.35969736026e-17
1.0
1.0


# Standardization of Only selected column. Here Standardizing the second column

In [55]:
y_scaled = preprocessing.scale(arr[:,1].reshape(-1,1))
print(y_scaled)

[[ 1.21386587]
 [-1.31939649]
 [ 0.64707196]
 [ 1.19903488]
 [-1.04169517]
 [-0.20189045]
 [ 0.91467749]
 [ 0.64707196]
 [-0.48075323]
 [-1.03720566]
 [ 0.91802786]
 [-0.76292172]
 [-0.47787191]
 [-0.19880811]
 [ 1.19930291]
 [-1.03733968]
 [ 0.08315936]
 [ 0.35983324]
 [ 0.35704126]
 [-0.76113486]
 [ 1.19534947]
 [-1.03821078]
 [ 0.93006687]
 [ 0.92566671]
 [ 1.20249694]
 [-1.59854964]
 [-1.59854964]
 [-1.59854964]
 [ 1.3602102 ]]


# Binarization of the entire dataset

In [56]:
#Binarization converts the given into a dataset of 0's and 1's depending on the value of threshold.
data_binarized= preprocessing.Binarizer(threshold=1).transform(arr)
print ("\nBinarized data =", data_binarized)


Binarized data = [[ 1.  1.]
 [ 0.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


# Binarization of Only perticular Column of the dataset. Here binarizing the second column using reshape function.

In [57]:
data_binarized= preprocessing.Binarizer(threshold=1).transform(arr[:,1].reshape(-1,1))
print(data_binarized)

[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
